name       : ruby-winrm-elevated
version    : 1.2.1
release    : 4
source     :
    - https://rubygems.org/downloads/winrm-elevated-1.2.1.gem : bb89e8e7ff6855d0f172380d9265706f8a44fdfecb02db535d6bdb3b74e65cf9
license    : Apache-2.0
component  : programming.ruby
summary    : RubyGem - winrm-elevated
description: |
    Ruby library for running commands via WinRM as elevated through a scheduled task.
builddeps  :
    - pkgconfig(ruby-2.7)
rundeps    :
    - ruby-winrm
    - ruby-winrm-fs
install    : |
    %gem_install
    rm -rf $installdir/$geminstalldir/{build_info,doc,extensions}
